### ISSUE TITLE
broken ios scrolling

### ISSUE THREAD

**Issue by frankville** [RyanMullins/angular-hammer#62]
Hello everyone, I'm working on an app that has a div with an absolute position, an overflow-y: scroll, z-index:1 and a hm-swipeleft attribute (sort of a navigation drawer that hides when swipe to the left). Everything works fine on all devices except in iOS  (safari and chrome). The problem I'm having is that the content of the div won't scroll unless I remove the hm-swipeleft attribute. I tried disabling preventDefault and stopPropagation with hm-recognizer-options but I couldn't get it to work. Here is a code sample to test 

 `<div style="height: 400px; width:100px; position:absolute; overflow-y:scroll; z-index:1;"  hm-swipeleft="toggleMenu">
        <button style="height:50px; width:100%;" ng-repeat="a in array ">{{a}}</button>
    </div>`

any ideas will be appreciated. Thanks in advance

**Comment by lsiric** [comment]
Prevent default does not work as an option because nobody mentioned hm-recognizer-options, when used in html, should be marked with SINGLE quotes, and attributes inside with DOUBLE quotes: 

`hm-recognizer-options='{"type":"swiperight","preventDefault":false}' `

If you take a closer look to 'official demo', you will notice this is the only property in html used with single quotes. 
I'd say this is a serious flaw with the documentation in general, because it seems a lot of people are having the same struggle, only because of this 'single quotes issue'.

cheers

**Comment by frankville** [comment]
Problem solved! Thank you very much.
